function OEM2L2_struct = save_OEM2L2(settings,curr_meas,proc_meas,ret_param,i)
%%
% save selected L2 parameters in a structure called OEM2L2 
OEM2L2 = struct('start_year',proc_meas.dataList(i).start_year, ...
                'start_month',proc_meas.dataList(i).start_month, ... 
                'start_day',proc_meas.dataList(i).start_day, ... 
                'start_hour',proc_meas.dataList(i).start_hour, ... 
                'start_min',proc_meas.dataList(i).start_min, ... 
                'start_sec',proc_meas.dataList(i).start_sec, ... 
                'mjd_start',proc_meas.dataList(i).mjd_start, ... 
                'end_year',proc_meas.dataList(i).end_year, ...
                'end_month',proc_meas.dataList(i).end_month, ... 
                'end_day',proc_meas.dataList(i).end_day, ... 
                'end_hour',proc_meas.dataList(i).end_hour, ... 
                'end_min',proc_meas.dataList(i).end_min, ... 
                'end_sec',proc_meas.dataList(i).end_sec, ... 
                'mjd_end',proc_meas.dataList(i).mjd_end, ... 
                'AvKe',ret_param.avk, ... 
                'species1_x',ret_param.species1_x, ... 
                'species1_xa',ret_param.species1_xa, ... 
                'zgrid',ret_param.zgrid);
save(fullfile(settings.OEM2L2_path, strcat('OEM2L2_',curr_meas.meas2str)), 'OEM2L2');

OEM2L2_struct.OEM2L2 = OEM2L2; 

end 
